steps:
- uses: actions/checkout@v3

- name: Set up JDK 1.8
  uses: actions/setup-java@v3
  with:
    java-version: 1.8

- name: Setup Android SDK
  uses: android-actions/setup-android@v2

- name: Git Sumbodule Update
  run: git submodule update --init

- name: Build M8Client
  run: ./gradlew --no-daemon build
